import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/Providers/Providers";

export const metadata: Metadata = {
  title: "EasyBank",
  description: "Generated by Montasir Mihad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-arp="">
      <body className={`font antialiased bg-white`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
